export const PACKAGING_LIST_REQUEST = 'PACKAGING_LIST_REQUEST'
export const PACKAGING_LIST_SUCCESS = 'PACKAGING_LIST_SUCCESS'
export const PACKAGING_LIST_FAIL = 'PACKAGING_LIST_FAIL'

export const PACKAGING_DETAILS_REQUEST = 'PACKAGING_DETAILS_REQUEST'
export const PACKAGING_DETAILS_SUCCESS = 'PACKAGING_DETAILS_SUCCESS'
export const PACKAGING_DETAILS_FAIL = 'PACKAGING_DETAILS_FAIL'

export const PACKAGING_DELETE_REQUEST = 'PACKAGING_DELETE_REQUEST'
export const PACKAGING_DELETE_SUCCESS = 'PACKAGING_DELETE_SUCCESS'
export const PACKAGING_DELETE_FAIL = 'PACKAGING_DELETE_FAIL'

export const PACKAGING_CREATE_REQUEST = 'PACKAGING_CREATE_REQUEST'
export const PACKAGING_CREATE_SUCCESS = 'PACKAGING_CREATE_SUCCESS'
export const PACKAGING_CREATE_FAIL = 'PACKAGING_CREATE_FAIL'
export const PACKAGING_CREATE_RESET = 'PACKAGING_CREATE_RESET'

export const PACKAGING_UPDATE_REQUEST = 'PACKAGING_UPDATE_REQUEST'
export const PACKAGING_UPDATE_SUCCESS = 'PACKAGING_UPDATE_SUCCESS'
export const PACKAGING_UPDATE_FAIL = 'PACKAGING_UPDATE_FAIL'
export const PACKAGING_UPDATE_RESET = 'PACKAGING_UPDATE_RESET'
